# Generated by Django 5.2.17 on 2026-09-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_experience"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sertifikasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=100)),
                ("platform", models.CharField(max_length=100)),
                ("ended_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
