# Generated by Django 5.2.17 on 2026-09-14 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_sertifikasi"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Sertifikasi",
            new_name="Certification",
        ),
    ]
