# Generated by Django 5.2.17 on 2026-09-14 10:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_rename_sertifikasi_certification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certification",
            name="ended_at",
        ),
        migrations.AddField(
            model_name="certification",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="certification",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="category",
            field=models.CharField(
                choices=[
                    ("internship", "Internship"),
                    ("research", "Research"),
                    ("volunteer", "Volunteer"),
                    ("part-time", "Part-Time"),
                    ("full-time", "Full-Time"),
                    ("freelance", "Freelance"),
                    ("event", "Event"),
                ],
                default="full-time",
                max_length=20,
            ),
        ),
    ]
